AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  IoTEnhancedCustomAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 5
Outputs:
  IoTEnhancedCustomAuthorizerArn:
    Description: ARN of the Lambda function
    Value: !GetAtt IoTEnhancedCustomAuthorizer.Arn
